<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['country_id' => 1, 'name' => 'Afghanistan', 'code' => 'AF'],
            ['country_id' => 2, 'name' => 'Åland Islands', 'code' => 'AX'],
            ['country_id' => 3, 'name' => 'Albania', 'code' => 'AL'],
            ['country_id' => 4, 'name' => 'Algeria', 'code' => 'DZ'],
            ['country_id' => 5, 'name' => 'American Samoa', 'code' => 'AS'],
            ['country_id' => 6, 'name' => 'Andorra', 'code' => 'AD'],
            ['country_id' => 7, 'name' => 'Angola', 'code' => 'AO'],
            ['country_id' => 8, 'name' => 'Anguilla', 'code' => 'AI'],
            ['country_id' => 9, 'name' => 'Antarctica', 'code' => 'AQ'],
            ['country_id' => 10, 'name' => 'Antigua and Barbuda', 'code' => 'AG'],
            ['country_id' => 11, 'name' => 'Argentina', 'code' => 'AR'],
            ['country_id' => 12, 'name' => 'Armenia', 'code' => 'AM'],
            ['country_id' => 13, 'name' => 'Aruba', 'code' => 'AW'],
            ['country_id' => 14, 'name' => 'Australia', 'code' => 'AU'],
            ['country_id' => 15, 'name' => 'Austria', 'code' => 'AT'],
            ['country_id' => 16, 'name' => 'Azerbaijan', 'code' => 'AZ'],
            ['country_id' => 17, 'name' => 'Bahamas', 'code' => 'BS'],
            ['country_id' => 18, 'name' => 'Bahrain', 'code' => 'BH'],
            ['country_id' => 19, 'name' => 'Bangladesh', 'code' => 'BD'],
            ['country_id' => 20, 'name' => 'Barbados', 'code' => 'BB'],
            ['country_id' => 21, 'name' => 'Belarus', 'code' => 'BY'],
            ['country_id' => 22, 'name' => 'Belgium', 'code' => 'BE'],
            ['country_id' => 23, 'name' => 'Belize', 'code' => 'BZ'],
            ['country_id' => 24, 'name' => 'Benin', 'code' => 'BJ'],
            ['country_id' => 25, 'name' => 'Bermuda', 'code' => 'BM'],
            ['country_id' => 26, 'name' => 'Bhutan', 'code' => 'BT'],
            ['country_id' => 27, 'name' => 'Bolivia', 'code' => 'BO'],
            ['country_id' => 28, 'name' => 'Bosnia and Herzegovina', 'code' => 'BA'],
            ['country_id' => 29, 'name' => 'Botswana', 'code' => 'BW'],
            ['country_id' => 30, 'name' => 'Bouvet Island', 'code' => 'BV'],
            ['country_id' => 31, 'name' => 'Brazil', 'code' => 'BR'],
            ['country_id' => 32, 'name' => 'British Indian Ocean Territory', 'code' => 'IO'],
            ['country_id' => 33, 'name' => 'Brunei Darussalam', 'code' => 'BN'],
            ['country_id' => 34, 'name' => 'Bulgaria', 'code' => 'BG'],
            ['country_id' => 35, 'name' => 'Burkina Faso', 'code' => 'BF'],
            ['country_id' => 36, 'name' => 'Burundi', 'code' => 'BI'],
            ['country_id' => 37, 'name' => 'Cambodia', 'code' => 'KH'],
            ['country_id' => 38, 'name' => 'Cameroon', 'code' => 'CM'],
            ['country_id' => 39, 'name' => 'Canada', 'code' => 'CA'],
            ['country_id' => 40, 'name' => 'Cape Verde', 'code' => 'CV'],
            ['country_id' => 41, 'name' => 'Cayman Islands', 'code' => 'KY'],
            ['country_id' => 42, 'name' => 'Central African Republic', 'code' => 'CF'],
            ['country_id' => 43, 'name' => 'Chad', 'code' => 'TD'],
            ['country_id' => 44, 'name' => 'Chile', 'code' => 'CL'],
            ['country_id' => 45, 'name' => 'China', 'code' => 'CN'],
            ['country_id' => 46, 'name' => 'Christmas Island', 'code' => 'CX'],
            ['country_id' => 47, 'name' => 'Cocos (Keeling) Islands', 'code' => 'CC'],
            ['country_id' => 48, 'name' => 'Colombia', 'code' => 'CO'],
            ['country_id' => 49, 'name' => 'Comoros', 'code' => 'KM'],
            ['country_id' => 50, 'name' => 'Congo', 'code' => 'CG'],
            ['country_id' => 51, 'name' => 'Congo (Democratic Republic)', 'code' => 'CD'],
            ['country_id' => 52, 'name' => 'Cook Islands', 'code' => 'CK'],
            ['country_id' => 53, 'name' => 'Costa Rica', 'code' => 'CR'],
            ['country_id' => 54, 'name' => 'Côte d\'Ivoire', 'code' => 'CI'],
            ['country_id' => 55, 'name' => 'Croatia', 'code' => 'HR'],
            ['country_id' => 56, 'name' => 'Cuba', 'code' => 'CU'],
            ['country_id' => 57, 'name' => 'Cyprus', 'code' => 'CY'],
            ['country_id' => 58, 'name' => 'Czech Republic', 'code' => 'CZ'],
            ['country_id' => 59, 'name' => 'Denmark', 'code' => 'DK'],
            ['country_id' => 60, 'name' => 'Djibouti', 'code' => 'DJ'],
            ['country_id' => 61, 'name' => 'Dominica', 'code' => 'DM'],
            ['country_id' => 62, 'name' => 'Dominican Republic', 'code' => 'DO'],
            ['country_id' => 63, 'name' => 'Ecuador', 'code' => 'EC'],
            ['country_id' => 64, 'name' => 'Egypt', 'code' => 'EG'],
            ['country_id' => 65, 'name' => 'El Salvador', 'code' => 'SV'],
            ['country_id' => 66, 'name' => 'Equatorial Guinea', 'code' => 'GQ'],
            ['country_id' => 67, 'name' => 'Eritrea', 'code' => 'ER'],
            ['country_id' => 68, 'name' => 'Estonia', 'code' => 'EE'],
            ['country_id' => 69, 'name' => 'Eswatini', 'code' => 'SZ'],
            ['country_id' => 70, 'name' => 'Ethiopia', 'code' => 'ET'],
            ['country_id' => 71, 'name' => 'Falkland Islands', 'code' => 'FK'],
            ['country_id' => 72, 'name' => 'Faroe Islands', 'code' => 'FO'],
            ['country_id' => 73, 'name' => 'Fiji', 'code' => 'FJ'],
            ['country_id' => 74, 'name' => 'Finland', 'code' => 'FI'],
            ['country_id' => 75, 'name' => 'France', 'code' => 'FR'],
            ['country_id' => 76, 'name' => 'Gabon', 'code' => 'GA'],
            ['country_id' => 77, 'name' => 'Gambia', 'code' => 'GM'],
            ['country_id' => 78, 'name' => 'Georgia', 'code' => 'GE'],
            ['country_id' => 79, 'name' => 'Germany', 'code' => 'DE'],
            ['country_id' => 80, 'name' => 'Ghana', 'code' => 'GH'],
            ['country_id' => 81, 'name' => 'Greece', 'code' => 'GR'],
            ['country_id' => 82, 'name' => 'Greenland', 'code' => 'GL'],
            ['country_id' => 83, 'name' => 'Grenada', 'code' => 'GD'],
            ['country_id' => 84, 'name' => 'Guadeloupe', 'code' => 'GP'],
            ['country_id' => 85, 'name' => 'Guam', 'code' => 'GU'],
            ['country_id' => 86, 'name' => 'Guatemala', 'code' => 'GT'],
            ['country_id' => 87, 'name' => 'Guernsey', 'code' => 'GG'],
            ['country_id' => 88, 'name' => 'Guinea', 'code' => 'GN'],
            ['country_id' => 89, 'name' => 'Guinea-Bissau', 'code' => 'GW'],
            ['country_id' => 90, 'name' => 'Guyana', 'code' => 'GY'],
            ['country_id' => 91, 'name' => 'Haiti', 'code' => 'HT'],
            ['country_id' => 92, 'name' => 'Heard Island and McDonald Islands', 'code' => 'HM'],
            ['country_id' => 93, 'name' => 'Holy See', 'code' => 'VA'],
            ['country_id' => 94, 'name' => 'Honduras', 'code' => 'HN'],
            ['country_id' => 95, 'name' => 'Hong Kong', 'code' => 'HK'],
            ['country_id' => 96, 'name' => 'Hungary', 'code' => 'HU'],
            ['country_id' => 97, 'name' => 'Iceland', 'code' => 'IS'],
            ['country_id' => 98, 'name' => 'India', 'code' => 'IN'],
            ['country_id' => 99, 'name' => 'Indonesia', 'code' => 'ID'],
            ['country_id' => 100, 'name' => 'Iran', 'code' => 'IR'],
            ['country_id' => 101, 'name' => 'Iraq', 'code' => 'IQ'],
            ['country_id' => 102, 'name' => 'Ireland', 'code' => 'IE'],
            ['country_id' => 103, 'name' => 'Isle of Man', 'code' => 'IM'],
            ['country_id' => 104, 'name' => 'Israel', 'code' => 'IL'],
            ['country_id' => 105, 'name' => 'Italy', 'code' => 'IT'],
            ['country_id' => 106, 'name' => 'Jamaica', 'code' => 'JM'],
            ['country_id' => 107, 'name' => 'Japan', 'code' => 'JP'],
            ['country_id' => 108, 'name' => 'Jersey', 'code' => 'JE'],
            ['country_id' => 109, 'name' => 'Jordan', 'code' => 'JO'],
            ['country_id' => 110, 'name' => 'Kazakhstan', 'code' => 'KZ'],
            ['country_id' => 111, 'name' => 'Kenya', 'code' => 'KE'],
            ['country_id' => 112, 'name' => 'Kiribati', 'code' => 'KI'],
            ['country_id' => 113, 'name' => 'Kuwait', 'code' => 'KW'],
            ['country_id' => 114, 'name' => 'Kyrgyzstan', 'code' => 'KG'],
            ['country_id' => 115, 'name' => 'Lao People\'s Democratic Republic', 'code' => 'LA'],
            ['country_id' => 116, 'name' => 'Latvia', 'code' => 'LV'],
            ['country_id' => 117, 'name' => 'Lebanon', 'code' => 'LB'],
            ['country_id' => 118, 'name' => 'Lesotho', 'code' => 'LS'],
            ['country_id' => 119, 'name' => 'Liberia', 'code' => 'LR'],
            ['country_id' => 120, 'name' => 'Libya', 'code' => 'LY'],
            ['country_id' => 121, 'name' => 'Liechtenstein', 'code' => 'LI'],
            ['country_id' => 122, 'name' => 'Lithuania', 'code' => 'LT'],
            ['country_id' => 123, 'name' => 'Luxembourg', 'code' => 'LU'],
            ['country_id' => 124, 'name' => 'Macao', 'code' => 'MO'],
            ['country_id' => 125, 'name' => 'Madagascar', 'code' => 'MG'],
            ['country_id' => 126, 'name' => 'Malawi', 'code' => 'MW'],
            ['country_id' => 127, 'name' => 'Malaysia', 'code' => 'MY'],
            ['country_id' => 128, 'name' => 'Maldives', 'code' => 'MV'],
            ['country_id' => 129, 'name' => 'Mali', 'code' => 'ML'],
            ['country_id' => 130, 'name' => 'Malta', 'code' => 'MT'],
            ['country_id' => 131, 'name' => 'Marshall Islands', 'code' => 'MH'],
            ['country_id' => 132, 'name' => 'Martinique', 'code' => 'MQ'],
            ['country_id' => 133, 'name' => 'Mauritania', 'code' => 'MR'],
            ['country_id' => 134, 'name' => 'Mauritius', 'code' => 'MU'],
            ['country_id' => 135, 'name' => 'Mayotte', 'code' => 'YT'],
            ['country_id' => 136, 'name' => 'Mexico', 'code' => 'MX'],
            ['country_id' => 137, 'name' => 'Micronesia', 'code' => 'FM'],
            ['country_id' => 138, 'name' => 'Moldova', 'code' => 'MD'],
            ['country_id' => 139, 'name' => 'Monaco', 'code' => 'MC'],
            ['country_id' => 140, 'name' => 'Mongolia', 'code' => 'MN'],
            ['country_id' => 141, 'name' => 'Montenegro', 'code' => 'ME'],
            ['country_id' => 142, 'name' => 'Montserrat', 'code' => 'MS'],
            ['country_id' => 143, 'name' => 'Morocco', 'code' => 'MA'],
            ['country_id' => 144, 'name' => 'Mozambique', 'code' => 'MZ'],
            ['country_id' => 145, 'name' => 'Myanmar', 'code' => 'MM'],
            ['country_id' => 146, 'name' => 'Namibia', 'code' => 'NA'],
            ['country_id' => 147, 'name' => 'Nauru', 'code' => 'NR'],
            ['country_id' => 148, 'name' => 'Nepal', 'code' => 'NP'],
            ['country_id' => 149, 'name' => 'Netherlands', 'code' => 'NL'],
            ['country_id' => 150, 'name' => 'New Caledonia', 'code' => 'NC'],
            ['country_id' => 151, 'name' => 'New Zealand', 'code' => 'NZ'],
            ['country_id' => 152, 'name' => 'Nicaragua', 'code' => 'NI'],
            ['country_id' => 153, 'name' => 'Niger', 'code' => 'NE'],
            ['country_id' => 154, 'name' => 'Nigeria', 'code' => 'NG'],
            ['country_id' => 155, 'name' => 'Niue', 'code' => 'NU'],
            ['country_id' => 156, 'name' => 'Norfolk Island', 'code' => 'NF'],
            ['country_id' => 157, 'name' => 'North Korea', 'code' => 'KP'],
            ['country_id' => 158, 'name' => 'North Macedonia', 'code' => 'MK'],
            ['country_id' => 159, 'name' => 'Northern Mariana Islands', 'code' => 'MP'],
            ['country_id' => 160, 'name' => 'Norway', 'code' => 'NO'],
            ['country_id' => 161, 'name' => 'Oman', 'code' => 'OM'],
            ['country_id' => 162, 'name' => 'Pakistan', 'code' => 'PK'],
            ['country_id' => 163, 'name' => 'Palau', 'code' => 'PW'],
            ['country_id' => 164, 'name' => 'Palestine', 'code' => 'PS'],
            ['country_id' => 165, 'name' => 'Panama', 'code' => 'PA'],
            ['country_id' => 166, 'name' => 'Papua New Guinea', 'code' => 'PG'],
            ['country_id' => 167, 'name' => 'Paraguay', 'code' => 'PY'],
            ['country_id' => 168, 'name' => 'Peru', 'code' => 'PE'],
            ['country_id' => 169, 'name' => 'Philippines', 'code' => 'PH'],
            ['country_id' => 170, 'name' => 'Pitcairn', 'code' => 'PN'],
            ['country_id' => 171, 'name' => 'Poland', 'code' => 'PL'],
            ['country_id' => 172, 'name' => 'Portugal', 'code' => 'PT'],
            ['country_id' => 173, 'name' => 'Puerto Rico', 'code' => 'PR'],
            ['country_id' => 174, 'name' => 'Qatar', 'code' => 'QA'],
            ['country_id' => 175, 'name' => 'Réunion', 'code' => 'RE'],
            ['country_id' => 176, 'name' => 'Romania', 'code' => 'RO'],
            ['country_id' => 177, 'name' => 'Russia', 'code' => 'RU'],
            ['country_id' => 178, 'name' => 'Rwanda', 'code' => 'RW'],
            ['country_id' => 179, 'name' => 'Saint Barthélemy', 'code' => 'BL'],
            ['country_id' => 180, 'name' => 'Saint Helena', 'code' => 'SH'],
            ['country_id' => 181, 'name' => 'Saint Kitts and Nevis', 'code' => 'KN'],
            ['country_id' => 182, 'name' => 'Saint Lucia', 'code' => 'LC'],
            ['country_id' => 183, 'name' => 'Saint Martin', 'code' => 'MF'],
            ['country_id' => 184, 'name' => 'Saint Pierre and Miquelon', 'code' => 'PM'],
            ['country_id' => 185, 'name' => 'Saint Vincent and the Grenadines', 'code' => 'VC'],
            ['country_id' => 186, 'name' => 'Samoa', 'code' => 'WS'],
            ['country_id' => 187, 'name' => 'San Marino', 'code' => 'SM'],
            ['country_id' => 188, 'name' => 'Sao Tome and Principe', 'code' => 'ST'],
            ['country_id' => 189, 'name' => 'Saudi Arabia', 'code' => 'SA'],
            ['country_id' => 190, 'name' => 'Senegal', 'code' => 'SN'],
            ['country_id' => 191, 'name' => 'Serbia', 'code' => 'RS'],
            ['country_id' => 192, 'name' => 'Seychelles', 'code' => 'SC'],
            ['country_id' => 193, 'name' => 'Sierra Leone', 'code' => 'SL'],
            ['country_id' => 194, 'name' => 'Singapore', 'code' => 'SG'],
            ['country_id' => 195, 'name' => 'Sint Maarten', 'code' => 'SX'],
            ['country_id' => 196, 'name' => 'Slovakia', 'code' => 'SK'],
            ['country_id' => 197, 'name' => 'Slovenia', 'code' => 'SI'],
            ['country_id' => 198, 'name' => 'Solomon Islands', 'code' => 'SB'],
            ['country_id' => 199, 'name' => 'Somalia', 'code' => 'SO'],
            ['country_id' => 200, 'name' => 'South Africa', 'code' => 'ZA'],
            ['country_id' => 201, 'name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS'],
            ['country_id' => 202, 'name' => 'South Korea', 'code' => 'KR'],
            ['country_id' => 203, 'name' => 'South Sudan', 'code' => 'SS'],
            ['country_id' => 204, 'name' => 'Spain', 'code' => 'ES'],
            ['country_id' => 205, 'name' => 'Sri Lanka', 'code' => 'LK'],
            ['country_id' => 206, 'name' => 'Sudan', 'code' => 'SD'],
            ['country_id' => 207, 'name' => 'Suriname', 'code' => 'SR'],
            ['country_id' => 208, 'name' => 'Svalbard and Jan Mayen', 'code' => 'SJ'],
            ['country_id' => 209, 'name' => 'Sweden', 'code' => 'SE'],
            ['country_id' => 210, 'name' => 'Switzerland', 'code' => 'CH'],
            ['country_id' => 211, 'name' => 'Syria', 'code' => 'SY'],
            ['country_id' => 212, 'name' => 'Taiwan', 'code' => 'TW'],
            ['country_id' => 213, 'name' => 'Tajikistan', 'code' => 'TJ'],
            ['country_id' => 214, 'name' => 'Tanzania', 'code' => 'TZ'],
            ['country_id' => 215, 'name' => 'Thailand', 'code' => 'TH'],
            ['country_id' => 216, 'name' => 'Timor-Leste', 'code' => 'TL'],
            ['country_id' => 217, 'name' => 'Togo', 'code' => 'TG'],
            ['country_id' => 218, 'name' => 'Tokelau', 'code' => 'TK'],
            ['country_id' => 219, 'name' => 'Tonga', 'code' => 'TO'],
            ['country_id' => 220, 'name' => 'Trinidad and Tobago', 'code' => 'TT'],
            ['country_id' => 221, 'name' => 'Tunisia', 'code' => 'TN'],
            ['country_id' => 222, 'name' => 'Turkey', 'code' => 'TR'],
            ['country_id' => 223, 'name' => 'Turkmenistan', 'code' => 'TM'],
            ['country_id' => 224, 'name' => 'Tuvalu', 'code' => 'TV'],
            ['country_id' => 225, 'name' => 'Uganda', 'code' => 'UG'],
            ['country_id' => 226, 'name' => 'Ukraine', 'code' => 'UA'],
            ['country_id' => 227, 'name' => 'United Arab Emirates', 'code' => 'AE'],
            ['country_id' => 228, 'name' => 'United Kingdom', 'code' => 'GB'],
            ['country_id' => 229, 'name' => 'United States', 'code' => 'US'],
            ['country_id' => 230, 'name' => 'Uruguay', 'code' => 'UY'],
            ['country_id' => 231, 'name' => 'Uzbekistan', 'code' => 'UZ'],
            ['country_id' => 232, 'name' => 'Vanuatu', 'code' => 'VU'],
            ['country_id' => 233, 'name' => 'Venezuela', 'code' => 'VE'],
            ['country_id' => 234, 'name' => 'Vietnam', 'code' => 'VN'],
            ['country_id' => 235, 'name' => 'British Virgin Islands', 'code' => 'VG'],
            ['country_id' => 236, 'name' => 'U.S. Virgin Islands', 'code' => 'VI'],
            ['country_id' => 237, 'name' => 'Wallis and Futuna', 'code' => 'WF'],
            ['country_id' => 238, 'name' => 'Western Sahara', 'code' => 'EH'],
            ['country_id' => 239, 'name' => 'Yemen', 'code' => 'YE'],
            ['country_id' => 240, 'name' => 'Zambia', 'code' => 'ZM'],
            ['country_id' => 241, 'name' => 'Zimbabwe', 'code' => 'ZW']
        ];

    DB::statement('SET FOREIGN_KEY_CHECKS=0;');
    DB::table('countries')->truncate();
    DB::table('countries')->insert($countries);
    DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
